import { DatabaseSchema } from './types';

// Initial seed data for Daily Delight
export const SEED: DatabaseSchema = {
  users: [
    {
      id: 'owner-1',
      name: 'Rajesh Kumar',
      email: 'owner@dailydelight.in',
      phone: '9876543210',
      password: 'owner123',
      role: 'owner',
      createdAt: new Date('2024-01-01').toISOString(),
    },
    {
      id: 'cust-1',
      name: 'Priya Sharma',
      email: 'priya@example.com',
      phone: '9123456780',
      password: 'priya123',
      role: 'customer',
      createdAt: new Date('2024-06-15').toISOString(),
    },
    {
      id: 'cust-2',
      name: 'Amit Verma',
      email: 'amit@example.com',
      phone: '9123456781',
      password: 'amit123',
      role: 'customer',
      createdAt: new Date('2024-07-10').toISOString(),
    },
    {
      id: 'cust-3',
      name: 'Sneha Patel',
      email: 'sneha@example.com',
      phone: '9123456782',
      password: 'sneha123',
      role: 'customer',
      createdAt: new Date('2024-08-01').toISOString(),
    },
  ],
  addresses: [
    {
      id: 'addr-1',
      userId: 'cust-1',
      label: 'Home',
      line1: 'B-204, Sunshine Apartments',
      line2: 'MG Road',
      city: 'Bengaluru',
      state: 'Karnataka',
      pincode: '560001',
      isDefault: true,
    },
    {
      id: 'addr-2',
      userId: 'cust-1',
      label: 'Office',
      line1: '5th Floor, Tech Park',
      line2: 'Whitefield',
      city: 'Bengaluru',
      state: 'Karnataka',
      pincode: '560066',
    },
    {
      id: 'addr-3',
      userId: 'cust-2',
      label: 'Home',
      line1: '12, Park View',
      line2: 'Sector 21',
      city: 'Bengaluru',
      state: 'Karnataka',
      pincode: '560001',
      isDefault: true,
    },
  ],
  categories: [
    { id: 'cat-veg', name: 'Vegetables', icon: '🥦', image: '🥦', order: 1, active: true },
    { id: 'cat-fruit', name: 'Fruits', icon: '🍎', image: '🍎', order: 2, active: true },
    { id: 'cat-dairy', name: 'Dairy & Eggs', icon: '🥛', image: '🥛', order: 3, active: true },
    { id: 'cat-bakery', name: 'Bakery', icon: '🍞', image: '🍞', order: 4, active: true },
    { id: 'cat-snacks', name: 'Snacks', icon: '🍪', image: '🍪', order: 5, active: true },
    { id: 'cat-beverage', name: 'Beverages', icon: '🥤', image: '🥤', order: 6, active: true },
    { id: 'cat-staples', name: 'Staples', icon: '🌾', image: '🌾', order: 7, active: true },
    { id: 'cat-spice', name: 'Spices', icon: '🌶️', image: '🌶️', order: 8, active: true },
    { id: 'cat-personal', name: 'Personal Care', icon: '🧴', image: '🧴', order: 9, active: true },
    { id: 'cat-cleaning', name: 'Cleaning', icon: '🧹', image: '🧹', order: 10, active: true },
  ],
  products: [
    // Vegetables
    { id: 'p-1', name: 'Fresh Tomato', description: 'Farm-fresh ripe tomatoes, perfect for curries and salads', categoryId: 'cat-veg', price: 32, mrp: 45, unit: '500 g', image: '🍅', stock: 120, active: true, featured: true, tags: ['bestseller'], createdAt: '2024-01-01', updatedAt: '2024-01-01' },
    { id: 'p-2', name: 'Onion', description: 'Premium quality red onions', categoryId: 'cat-veg', price: 28, mrp: 38, unit: '1 kg', image: '🧅', stock: 200, active: true, featured: true, tags: [], createdAt: '2024-01-01', updatedAt: '2024-01-01' },
    { id: 'p-3', name: 'Potato', description: 'Fresh potatoes, great for frying and boiling', categoryId: 'cat-veg', price: 25, mrp: 35, unit: '1 kg', image: '🥔', stock: 180, active: true, featured: false, tags: [], createdAt: '2024-01-01', updatedAt: '2024-01-01' },
    { id: 'p-4', name: 'Green Chilli', description: 'Spicy fresh green chillies', categoryId: 'cat-veg', price: 15, mrp: 20, unit: '100 g', image: '🌶️', stock: 90, active: true, featured: false, tags: [], createdAt: '2024-01-01', updatedAt: '2024-01-01' },
    { id: 'p-5', name: 'Spinach', description: 'Tender baby spinach leaves, washed and ready', categoryId: 'cat-veg', price: 35, mrp: 50, unit: '250 g', image: '🥬', stock: 60, active: true, featured: true, tags: ['fresh'], createdAt: '2024-01-01', updatedAt: '2024-01-01' },
    { id: 'p-6', name: 'Carrot', description: 'Crunchy orange carrots, rich in beta-carotene', categoryId: 'cat-veg', price: 40, mrp: 55, unit: '500 g', image: '🥕', stock: 75, active: true, featured: false, tags: [], createdAt: '2024-01-01', updatedAt: '2024-01-01' },

    // Fruits
    { id: 'p-7', name: 'Banana', description: 'Sweet ripe bananas, perfect for breakfast', categoryId: 'cat-fruit', price: 45, mrp: 60, unit: '6 pcs', image: '🍌', stock: 100, active: true, featured: true, tags: ['bestseller'], createdAt: '2024-01-01', updatedAt: '2024-01-01' },
    { id: 'p-8', name: 'Apple', description: 'Crispy red apples from Kashmir', categoryId: 'cat-fruit', price: 180, mrp: 220, unit: '1 kg', image: '🍎', stock: 50, active: true, featured: true, tags: ['premium'], createdAt: '2024-01-01', updatedAt: '2024-01-01' },
    { id: 'p-9', name: 'Mango', description: 'Sweet Alphonso mangoes', categoryId: 'cat-fruit', price: 350, mrp: 450, unit: '1 kg', image: '🥭', stock: 30, active: true, featured: true, tags: ['seasonal'], createdAt: '2024-01-01', updatedAt: '2024-01-01' },
    { id: 'p-10', name: 'Orange', description: 'Juicy Nagpur oranges', categoryId: 'cat-fruit', price: 90, mrp: 120, unit: '500 g', image: '🍊', stock: 80, active: true, featured: false, tags: [], createdAt: '2024-01-01', updatedAt: '2024-01-01' },

    // Dairy
    { id: 'p-11', name: 'Full Cream Milk', description: 'Pasteurized toned milk', categoryId: 'cat-dairy', price: 32, mrp: 35, unit: '500 ml', image: '🥛', stock: 200, active: true, featured: true, tags: ['bestseller'], createdAt: '2024-01-01', updatedAt: '2024-01-01' },
    { id: 'p-12', name: 'Curd', description: 'Fresh set dahi in cup', categoryId: 'cat-dairy', price: 35, mrp: 40, unit: '400 g', image: '🍶', stock: 60, active: true, featured: false, tags: [], createdAt: '2024-01-01', updatedAt: '2024-01-01' },
    { id: 'p-13', name: 'Paneer', description: 'Soft fresh paneer, ready to cook', categoryId: 'cat-dairy', price: 95, mrp: 110, unit: '200 g', image: '🧀', stock: 40, active: true, featured: true, tags: [], createdAt: '2024-01-01', updatedAt: '2024-01-01' },
    { id: 'p-14', name: 'Eggs', description: 'Farm fresh brown eggs', categoryId: 'cat-dairy', price: 78, mrp: 90, unit: '12 pcs', image: '🥚', stock: 90, active: true, featured: false, tags: [], createdAt: '2024-01-01', updatedAt: '2024-01-01' },
    { id: 'p-15', name: 'Butter', description: 'Salted butter', categoryId: 'cat-dairy', price: 55, mrp: 60, unit: '100 g', image: '🧈', stock: 75, active: true, featured: false, tags: [], createdAt: '2024-01-01', updatedAt: '2024-01-01' },

    // Bakery
    { id: 'p-16', name: 'Brown Bread', description: 'Whole wheat brown bread, soft and fresh', categoryId: 'cat-bakery', price: 50, mrp: 60, unit: '400 g', image: '🍞', stock: 40, active: true, featured: true, tags: ['bestseller'], createdAt: '2024-01-01', updatedAt: '2024-01-01' },
    { id: 'p-17', name: 'White Bread', description: 'Soft sandwich bread', categoryId: 'cat-bakery', price: 45, mrp: 55, unit: '400 g', image: '🍞', stock: 35, active: true, featured: false, tags: [], createdAt: '2024-01-01', updatedAt: '2024-01-01' },
    { id: 'p-18', name: 'Croissant', description: 'Buttery flaky croissants', categoryId: 'cat-bakery', price: 80, mrp: 100, unit: '2 pcs', image: '🥐', stock: 20, active: true, featured: false, tags: [], createdAt: '2024-01-01', updatedAt: '2024-01-01' },
    { id: 'p-19', name: 'Cookies', description: 'Choco chip cookies', categoryId: 'cat-bakery', price: 60, mrp: 75, unit: '120 g', image: '🍪', stock: 50, active: true, featured: false, tags: [], createdAt: '2024-01-01', updatedAt: '2024-01-01' },

    // Snacks
    { id: 'p-20', name: 'Potato Chips', description: 'Classic salted potato chips', categoryId: 'cat-snacks', price: 20, mrp: 25, unit: '50 g', image: '🥔', stock: 150, active: true, featured: false, tags: [], createdAt: '2024-01-01', updatedAt: '2024-01-01' },
    { id: 'p-21', name: 'Chocolate Bar', description: 'Milk chocolate bar', categoryId: 'cat-snacks', price: 40, mrp: 50, unit: '40 g', image: '🍫', stock: 200, active: true, featured: true, tags: ['bestseller'], createdAt: '2024-01-01', updatedAt: '2024-01-01' },
    { id: 'p-22', name: 'Biscuits', description: 'Cream biscuits', categoryId: 'cat-snacks', price: 30, mrp: 35, unit: '100 g', image: '🍪', stock: 180, active: true, featured: false, tags: [], createdAt: '2024-01-01', updatedAt: '2024-01-01' },

    // Beverages
    { id: 'p-23', name: 'Cola', description: 'Carbonated cola drink', categoryId: 'cat-beverage', price: 65, mrp: 75, unit: '1.25 L', image: '🥤', stock: 120, active: true, featured: true, tags: [], createdAt: '2024-01-01', updatedAt: '2024-01-01' },
    { id: 'p-24', name: 'Orange Juice', description: '100% pure orange juice', categoryId: 'cat-beverage', price: 110, mrp: 130, unit: '1 L', image: '🧃', stock: 60, active: true, featured: false, tags: [], createdAt: '2024-01-01', updatedAt: '2024-01-01' },
    { id: 'p-25', name: 'Mineral Water', description: 'Packaged drinking water', categoryId: 'cat-beverage', price: 20, mrp: 25, unit: '1 L', image: '💧', stock: 300, active: true, featured: false, tags: [], createdAt: '2024-01-01', updatedAt: '2024-01-01' },
    { id: 'p-26', name: 'Green Tea', description: 'Premium green tea bags', categoryId: 'cat-beverage', price: 180, mrp: 220, unit: '25 bags', image: '🍵', stock: 70, active: true, featured: false, tags: [], createdAt: '2024-01-01', updatedAt: '2024-01-01' },

    // Staples
    { id: 'p-27', name: 'Basmati Rice', description: 'Premium long grain basmati rice', categoryId: 'cat-staples', price: 165, mrp: 195, unit: '1 kg', image: '🍚', stock: 100, active: true, featured: true, tags: ['bestseller'], createdAt: '2024-01-01', updatedAt: '2024-01-01' },
    { id: 'p-28', name: 'Whole Wheat Atta', description: '100% whole wheat flour', categoryId: 'cat-staples', price: 240, mrp: 290, unit: '5 kg', image: '🌾', stock: 60, active: true, featured: true, tags: [], createdAt: '2024-01-01', updatedAt: '2024-01-01' },
    { id: 'p-29', name: 'Sugar', description: 'Refined sugar', categoryId: 'cat-staples', price: 48, mrp: 55, unit: '1 kg', image: '🍬', stock: 120, active: true, featured: false, tags: [], createdAt: '2024-01-01', updatedAt: '2024-01-01' },
    { id: 'p-30', name: 'Cooking Oil', description: 'Refined sunflower oil', categoryId: 'cat-staples', price: 165, mrp: 190, unit: '1 L', image: '🛢️', stock: 80, active: true, featured: true, tags: [], createdAt: '2024-01-01', updatedAt: '2024-01-01' },
    { id: 'p-31', name: 'Salt', description: 'Iodized salt', categoryId: 'cat-staples', price: 22, mrp: 28, unit: '1 kg', image: '🧂', stock: 200, active: true, featured: false, tags: [], createdAt: '2024-01-01', updatedAt: '2024-01-01' },

    // Spices
    { id: 'p-32', name: 'Turmeric Powder', description: 'Pure turmeric powder', categoryId: 'cat-spice', price: 45, mrp: 55, unit: '100 g', image: '🟡', stock: 100, active: true, featured: false, tags: [], createdAt: '2024-01-01', updatedAt: '2024-01-01' },
    { id: 'p-33', name: 'Red Chilli Powder', description: 'Spicy red chilli powder', categoryId: 'cat-spice', price: 60, mrp: 75, unit: '100 g', image: '🔴', stock: 90, active: true, featured: false, tags: [], createdAt: '2024-01-01', updatedAt: '2024-01-01' },
    { id: 'p-34', name: 'Garam Masala', description: 'Aromatic spice blend', categoryId: 'cat-spice', price: 80, mrp: 100, unit: '100 g', image: '🟤', stock: 80, active: true, featured: false, tags: [], createdAt: '2024-01-01', updatedAt: '2024-01-01' },
    { id: 'p-35', name: 'Cumin Seeds', description: 'Whole cumin seeds', categoryId: 'cat-spice', price: 70, mrp: 90, unit: '100 g', image: '🟫', stock: 70, active: true, featured: false, tags: [], createdAt: '2024-01-01', updatedAt: '2024-01-01' },

    // Personal Care
    { id: 'p-36', name: 'Shampoo', description: 'Herbal shampoo, 200ml', categoryId: 'cat-personal', price: 120, mrp: 150, unit: '200 ml', image: '🧴', stock: 60, active: true, featured: false, tags: [], createdAt: '2024-01-01', updatedAt: '2024-01-01' },
    { id: 'p-37', name: 'Toothpaste', description: 'Fresh mint toothpaste', categoryId: 'cat-personal', price: 85, mrp: 100, unit: '150 g', image: '🪥', stock: 80, active: true, featured: false, tags: [], createdAt: '2024-01-01', updatedAt: '2024-01-01' },
    { id: 'p-38', name: 'Hand Wash', description: 'Liquid hand wash, refreshing', categoryId: 'cat-personal', price: 95, mrp: 120, unit: '250 ml', image: '🧼', stock: 50, active: true, featured: false, tags: [], createdAt: '2024-01-01', updatedAt: '2024-01-01' },

    // Cleaning
    { id: 'p-39', name: 'Dish Wash Liquid', description: 'Lemon fresh dish wash gel', categoryId: 'cat-cleaning', price: 75, mrp: 90, unit: '500 ml', image: '🍋', stock: 70, active: true, featured: false, tags: [], createdAt: '2024-01-01', updatedAt: '2024-01-01' },
    { id: 'p-40', name: 'Floor Cleaner', description: 'Disinfectant floor cleaner', categoryId: 'cat-cleaning', price: 110, mrp: 130, unit: '1 L', image: '🧹', stock: 45, active: true, featured: false, tags: [], createdAt: '2024-01-01', updatedAt: '2024-01-01' },
  ],
  carts: [],
  orders: [
    {
      id: 'ord-1001',
      userId: 'cust-1',
      customerName: 'Priya Sharma',
      customerPhone: '9123456780',
      items: [
        { productId: 'p-1', name: 'Fresh Tomato', price: 32, quantity: 2, unit: '500 g', image: '🍅' },
        { productId: 'p-11', name: 'Full Cream Milk', price: 32, quantity: 3, unit: '500 ml', image: '🥛' },
        { productId: 'p-16', name: 'Brown Bread', price: 50, quantity: 1, unit: '400 g', image: '🍞' },
      ],
      subtotal: 210,
      deliveryFee: 25,
      handlingFee: 5,
      discount: 25,
      couponCode: 'WELCOME25',
      total: 215,
      address: {
        id: 'addr-1',
        userId: 'cust-1',
        label: 'Home',
        line1: 'B-204, Sunshine Apartments',
        line2: 'MG Road',
        city: 'Bengaluru',
        state: 'Karnataka',
        pincode: '560001',
        isDefault: true,
      },
      paymentMethod: 'upi',
      paymentStatus: 'paid',
      status: 'delivered',
      placedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
      timeline: [
        { status: 'placed', at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString() },
        { status: 'confirmed', at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000 + 60000).toISOString() },
        { status: 'packed', at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000 + 300000).toISOString() },
        { status: 'out_for_delivery', at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000 + 600000).toISOString() },
        { status: 'delivered', at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000 + 1200000).toISOString() },
      ],
    },
    {
      id: 'ord-1002',
      userId: 'cust-2',
      customerName: 'Amit Verma',
      customerPhone: '9123456781',
      items: [
        { productId: 'p-7', name: 'Banana', price: 45, quantity: 1, unit: '6 pcs', image: '🍌' },
        { productId: 'p-13', name: 'Paneer', price: 95, quantity: 1, unit: '200 g', image: '🧀' },
        { productId: 'p-27', name: 'Basmati Rice', price: 165, quantity: 1, unit: '1 kg', image: '🍚' },
      ],
      subtotal: 305,
      deliveryFee: 0,
      handlingFee: 5,
      discount: 0,
      total: 310,
      address: {
        id: 'addr-3',
        userId: 'cust-2',
        label: 'Home',
        line1: '12, Park View',
        line2: 'Sector 21',
        city: 'Bengaluru',
        state: 'Karnataka',
        pincode: '560001',
        isDefault: true,
      },
      paymentMethod: 'cod',
      paymentStatus: 'pending',
      status: 'out_for_delivery',
      placedAt: new Date(Date.now() - 3600000).toISOString(),
      timeline: [
        { status: 'placed', at: new Date(Date.now() - 3600000).toISOString() },
        { status: 'confirmed', at: new Date(Date.now() - 3500000).toISOString() },
        { status: 'packed', at: new Date(Date.now() - 3000000).toISOString() },
        { status: 'out_for_delivery', at: new Date(Date.now() - 600000).toISOString() },
      ],
    },
    {
      id: 'ord-1003',
      userId: 'cust-3',
      customerName: 'Sneha Patel',
      customerPhone: '9123456782',
      items: [
        { productId: 'p-8', name: 'Apple', price: 180, quantity: 1, unit: '1 kg', image: '🍎' },
        { productId: 'p-21', name: 'Chocolate Bar', price: 40, quantity: 2, unit: '40 g', image: '🍫' },
      ],
      subtotal: 260,
      deliveryFee: 25,
      handlingFee: 5,
      discount: 0,
      total: 290,
      address: {
        id: 'a-sneha-1',
        userId: 'cust-3',
        label: 'Home',
        line1: 'B-12, Skyline',
        line2: 'Indiranagar',
        city: 'Bengaluru',
        state: 'Karnataka',
        pincode: '560038',
        isDefault: true,
      },
      paymentMethod: 'upi',
      paymentStatus: 'paid',
      status: 'placed',
      placedAt: new Date(Date.now() - 600000).toISOString(),
      timeline: [
        { status: 'placed', at: new Date(Date.now() - 600000).toISOString() },
      ],
    },
  ],
  coupons: [
    {
      id: 'cp-1',
      code: 'WELCOME25',
      description: 'Flat ₹25 off on your first order',
      type: 'flat',
      value: 25,
      minOrder: 100,
      active: true,
      validFrom: '2024-01-01',
      validTill: '2025-12-31',
      usageLimit: 1000,
      usedCount: 145,
      createdAt: '2024-01-01',
    },
    {
      id: 'cp-2',
      code: 'FRESH20',
      description: '20% off up to ₹50 on fresh produce',
      type: 'percent',
      value: 20,
      minOrder: 200,
      maxDiscount: 50,
      active: true,
      validFrom: '2024-06-01',
      validTill: '2025-06-30',
      usageLimit: 500,
      usedCount: 89,
      createdAt: '2024-06-01',
    },
    {
      id: 'cp-3',
      code: 'FREEDEL',
      description: 'Free delivery on orders above ₹199',
      type: 'flat',
      value: 25,
      minOrder: 199,
      active: true,
      validFrom: '2024-08-01',
      validTill: '2025-08-31',
      usedCount: 234,
      createdAt: '2024-08-01',
    },
    {
      id: 'cp-4',
      code: 'MEGA50',
      description: 'Flat ₹50 off on orders above ₹500',
      type: 'flat',
      value: 50,
      minOrder: 500,
      active: false,
      validFrom: '2024-10-01',
      validTill: '2024-12-31',
      usedCount: 12,
      createdAt: '2024-10-01',
    },
  ],
  deliveryAreas: [
    { id: 'da-1', pincode: '560001', area: 'MG Road', city: 'Bengaluru', deliveryRadius: 5, estimatedTime: 15, active: true, deliveryFee: 25, freeAbove: 199 },
    { id: 'da-2', pincode: '560066', area: 'Whitefield', city: 'Bengaluru', deliveryRadius: 7, estimatedTime: 20, active: true, deliveryFee: 30, freeAbove: 299 },
    { id: 'da-3', pincode: '560038', area: 'Indiranagar', city: 'Bengaluru', deliveryRadius: 6, estimatedTime: 18, active: true, deliveryFee: 25, freeAbove: 199 },
    { id: 'da-4', pincode: '560034', area: 'Koramangala', city: 'Bengaluru', deliveryRadius: 6, estimatedTime: 18, active: true, deliveryFee: 25, freeAbove: 199 },
    { id: 'da-5', pincode: '560011', area: 'Jayanagar', city: 'Bengaluru', deliveryRadius: 8, estimatedTime: 25, active: false, deliveryFee: 35, freeAbove: 399 },
  ],
  banners: [
    { id: 'b-1', title: 'Fresh Veggies at ₹25!', subtitle: 'Limited time offer on selected items', image: '🥦', color: '#0C831F', active: true, order: 1 },
    { id: 'b-2', title: 'Free Delivery', subtitle: 'On orders above ₹199', image: '🚚', color: '#FF6B35', active: true, order: 2 },
    { id: 'b-3', title: '20% OFF on Fruits', subtitle: 'Use code FRESH20', image: '🍎', color: '#9C27B0', active: true, order: 3 },
    { id: 'b-4', title: 'Daily Essentials', subtitle: 'Milk, bread, eggs at your door', image: '🥛', color: '#2196F3', active: true, order: 4 },
  ],
  settings: {
    storeName: 'Daily Delight',
    storePhone: '1800-123-4567',
    storeAddress: 'Shop 12, MG Road, Bengaluru 560001',
    storeEmail: 'hello@dailydelight.in',
    deliveryRadiusKm: 8,
    baseDeliveryFee: 25,
    freeDeliveryAbove: 199,
    handlingFee: 5,
    codEnabled: true,
    upiEnabled: true,
    cardEnabled: true,
    walletEnabled: true,
    minOrderValue: 50,
    gstPercent: 5,
    notificationsEnabled: true,
  },
  session: null,
};
